In [64]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os 
%matplotlib inline
import sklearn

### Current samples times above the threshold

In [82]:
ds1 = pd.read_csv('data/AllSites.csv')
threshold = np.where(ds1['NP_Cya_bio'] >= 4e8)
target = np.zeros(len(ds1['NP_Cya_bio']))
target[threshold] = 1
ds1['target'] = pd.Series(target)
ds1 = ds1.dropna(axis=0, how='any')

In [83]:
t = np.where(ds1['target'] == 1.0)
ds1.iloc[t]

,StationID,Station,Date,Time,Stratum,Depth,TP,DP,Cl,TN,TempC,Chla,Secchi,NP_Cya_bio,target
936,9,Otter Creek Segment,8/18/11,1235.0,E,4.6,15.7,9.3,12.6,H0.35,22.1,10.4,2.3,4.260000e+08,1.0
3037,40,St. Albans Bay,8/6/14,1210.0,U,2.2,37,12.1,10.6,0.74,24.7,28.2,1.1,7.110000e+08,1.0
3038,40,St. Albans Bay,8/19/14,1010.0,U,2.6,41.7,13.5,10.9,0.61,20.5,25.38,1.3,7.280000e+08,1.0
3269,50,Missisquoi Bay,9/22/06,1100.0,U,2.2,75.5,23.2,6.7,0.64,17.3,36,1.1,4.230000e+08,1.0
3271,50,Missisquoi Bay,10/6/06,1100.0,U,2.6,69.4,33.6,7.3,0.63,13.0,12.6,1.3,7.050000e+08,1.0
3307,50,Missisquoi Bay,8/20/08,1050.0,U,2,66.4,16.6,5.9,0.74,21.3,44.9,1,1.260000e+09,1.0
3400,50,Missisquoi Bay,7/30/13,1020.0,U,3,40.2,16,7.7,0.8,23.8,45.03,1.5,1.170000e+09,1.0
3461,51,Missisquoi Bay Central,9/7/06,1055.0,U,2.4,62.9,18,6.3,0.77,19.3,3.73,1.2,4.380000e+08,1.0
3464,51,Missisquoi Bay Central,9/22/06,1040.0,U,2,73.7,19.5,6.6,0.8,17.3,42.4,0.8,1.540000e+09,1.0
3499,51,Missisquoi Bay Central,8/6/08,1115.0,U,2,74.1,29.7,7.1,0.81,23.2,45.5,1.1,1.190000e+09,1.0
3556,51,Missisquoi Bay Central,8/12/11,1105.0,U,3,61.4,20,6,H0.55,23.5,J31.8,1.5,5.190000e+08,1.0
3574,51,Missisquoi Bay Central,8/6/12,1050.0,U,1.8,109,46.8,7.5,0.61,25.5,H33.27,0.9,4.150000e+08,1.0
3575,51,Missisquoi Bay Central,8/21/12,1245.0,U,1,H88.7,20.1,7.8,H0.87,23.1,H113.1,0.5,1.670000e+09,1.0
3610,51,Missisquoi Bay Central,8/20/14,1100.0,U,1.8,96.1,29.5,8.5,1.04,20.6,34.73,0.9,7.340000e+08,1.0
3624,51,Missisquoi Bay Central,7/20/15,1132.0,U,2.4,48.7,22.7,8.1,0.83,24.1,21.63,1.2,4.880000e+08,1.0
3627,51,Missisquoi Bay Central,8/6/15,1103.0,U,2.2,67.4,25.8,7.7,0.71,23.4,42.08,1.1,4.720000e+08,1.0
3632,51,Missisquoi Bay Central,9/17/15,1100.0,U,2,94.2,40.7,8.7,0.9,22.3,50.16,1,4.430000e+08,1.0

### This almost works... it rounds some of the floats too much, will continue to address.

In [99]:
ds2 = ds1.drop(['Station', 'Stratum','Date','StationID','Time'], axis=1)
# ds2
ds2['Depth'] = ds1['Depth'].astype(str).str.extract('(\d+)').astype(float)
ds2['TP'] = ds1['TP'].astype(str).str.extract('(\d+)').astype(float)
ds2['Cl'] = ds1['Cl'].astype(str).str.extract('(\d+)').astype(float)
ds2['DP'] = ds1['DP'].astype(str).str.extract('(\d+)').astype(float)
ds2['TN'] = ds1['TN'].astype(str).str.extract('(\d+)').astype(float)
ds2['TempC'] = ds1['TempC'].astype(str).str.extract('(\d+)').astype(float)
ds2['Chla'] = ds1['Chla'].astype(str).str.extract('(\d+)').astype(float)
ds2['Chla'] = ds1['Chla'].astype(str).str.extract('(\d+)').astype(float)
ds2['Secchi'] = ds1['Secchi'].astype(str).str.extract('(\d+)').astype(float)
y = np.array(ds2['target'])
X = np.array(ds2.drop(['target'], axis=1))
# ds1.iloc[t]
ds2

      Depth     TP    DP    Cl   TN  TempC  Chla  Secchi   NP_Cya_bio  target
1       2.0   36.0  14.0  17.0  0.0   13.0   9.0     1.0          0.0     0.0
2       2.0   50.0  27.0  12.0  0.0   14.0   2.0     0.0          0.0     0.0
4       2.0   59.0  32.0  12.0  0.0   17.0   4.0     0.0          0.0     0.0
5       1.0   77.0  47.0  10.0  0.0   22.0   1.0     0.0          0.0     0.0
7       2.0  107.0  49.0  10.0  0.0   21.0   2.0     0.0     741000.0     0.0
...     ...    ...   ...   ...  ...    ...   ...     ...          ...     ...
3629    2.0   53.0  16.0   8.0  0.0   25.0  27.0     1.0  389000000.0     0.0
3631    2.0   83.0  33.0   8.0  0.0   23.0  23.0     1.0  133000000.0     0.0
3632    2.0   94.0  40.0   8.0  0.0   22.0  50.0     1.0  443000000.0     1.0
3634    2.0   68.0  42.0   9.0  0.0   13.0  10.0     1.0    9460000.0     0.0
3636    2.0   79.0  49.0   9.0  0.0    9.0  11.0     1.0    6510000.0     0.0

[1298 rows x 10 columns]

### Not Used

In [11]:

# ds2 = ds1.drop(['target', 'Station', 'Stratum','Date','StationID','Time'], axis=1)
# for col in ds2.columns:
#     if type(ds2[col][0]) == 'String':
#         for j, str_item in enumerate(ds2[col]):
#             print(str_item)
#             if str_item[0] == 'H':
#                 print(str_item)
#                 new_str=str_item.pop[0]
#                 ds2[col][j] = new_str
# # with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
# #     print(ds2)

In [15]:
# threshold = np.where(ds1['NP_Cya_bio'] >= 4e8)
# target = np.zeros(len(ds1['NP_Cya_bio']))
# target[threshold] = 1
# ds1['target'] = pd.Series(target)
# ds1.iloc[threshold]
# y = np.array(ds1['target'])
# X = np.array(ds1.drop(['target', 'Station', 'Stratum','Date','StationID'], axis=1))
# # with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
# #     print(ds1)
# # for i,x in enumerate(X):
# #     X[i] = x.astype(np.float64)
# ds1

,StationID,Station,Date,Time,Stratum,Depth,TP,DP,Cl,TN,TempC,Chla,Secchi,NP_Cya_bio,target
0,2,South Lake B,4/12/06,1055.0,U,2,39.2,16.2,13,0.61,NaN,1.41,0.5,0.0,0.0
1,2,South Lake B,5/2/06,1050.0,U,2.2,36.8,14.8,17.5,0.45,13.7,9.67,1.1,0.0,0.0
2,2,South Lake B,5/25/06,1100.0,U,2,50.1,27.4,12.1,0.55,14.5,2.04,0.7,0.0,0.0
3,2,South Lake B,6/8/06,1250.0,U,2,62.6,33.6,11.9,0.6,NaN,2.54,0.8,NaN,0.0
4,2,South Lake B,6/8/06,1105.0,U,2,59.6,32.6,12,0.65,17.7,4.13,0.6,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3632,51,Missisquoi Bay Central,9/17/15,1100.0,U,2,94.2,40.7,8.7,0.9,22.3,50.16,1,443000000.0,1.0
3633,51,Missisquoi Bay Central,9/18/15,1030.0,U,2,90.8,33.8,8.7,0.72,22.2,29.84,1,NaN,0.0
3634,51,Missisquoi Bay Central,10/7/15,1042.0,U,2.8,68.8,42.6,9.6,0.74,13.4,10.22,1.4,9460000.0,0.0
3635,51,Missisquoi Bay Central,10/8/15,1030.0,U,3.2,70.7,44,9.7,0.72,13.2,7.12,1.6,NaN,0.0
3636,51,Missisquoi Bay Central,10/21/15,1123.0,U,2.6,79.4,49.7,9.2,0.76,9.2,11.81,1.3,6510000.0,0.0

### Simple SVM Testing

In [98]:
from sklearn import svm
from sklearn import preprocessing
from sklearn import metrics
from sklearn.model_selection import cross_val_score, cross_val_predict

X_normalized = preprocessing.normalize(X) # normalize X for processing
kernels = ['linear', 'poly', 'rbf', 'sigmoid']
print('C=5\n')
for kernel in kernels:
    svm_classifer = svm.SVC(C=5, kernel=kernel)
    y_predicted = cross_val_predict(svm_classifer, X, y, cv=10)
    print(f'KERNEL: {kernel}')
    print(metrics.classification_report(y, y_predicted))
    print(metrics.confusion_matrix(y, y_predicted))
    print('\n')
print('C=50\n')
for kernel in kernels:
    svm_classifer = svm.SVC(C=50, kernel=kernel)
    y_predicted = cross_val_predict(svm_classifer, X, y, cv=5)
    print(f'KERNEL: {kernel}')
    print(metrics.classification_report(y, y_predicted))
    print(metrics.confusion_matrix(y, y_predicted))
    print('\n')

C=5

KERNEL: linear
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1281
         1.0       0.89      1.00      0.94        17

    accuracy                           1.00      1298
   macro avg       0.95      1.00      0.97      1298
weighted avg       1.00      1.00      1.00      1298

[[1279    2]
 [   0   17]]


KERNEL: poly
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1281
         1.0       0.89      1.00      0.94        17

    accuracy                           1.00      1298
   macro avg       0.95      1.00      0.97      1298
weighted avg       1.00      1.00      1.00      1298

[[1279    2]
 [   0   17]]


KERNEL: rbf
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1281
         1.0       0.89      1.00      0.94        17

    accuracy                           1.00      1298
   macro avg       0.95      1.00      0.97      1298
weighted avg       1.00      1.00      1.00      1298

[[1279    2]
 [   0   17]]


KERNEL: sigmoid
              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99      1281
         1.0       0.00      0.00      0.00        17

    accuracy                           0.98      1298
   macro avg       0.49      0.50      0.50      1298
weighted avg       0.97      0.98      0.98      1298

[[1273    8]
 [  17    0]]


C=50

KERNEL: linear
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1281
         1.0       0.89      1.00      0.94        17

    accuracy                           1.00      1298
   macro avg       0.95      1.00      0.97      1298
weighted avg       1.00      1.00      1.00      1298

[[1279    2]
 [   0   17]]


KERNEL: poly
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1281
         1.0       0.89      1.00      0.94        17

    accuracy                           1.00      1298
   macro avg       0.95      1.00      0.97      1298
weighted avg       1.00      1.00      1.00      1298

[[1279    2]
 [   0   17]]


KERNEL: rbf
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1281
         1.0       0.89      1.00      0.94        17

    accuracy                           1.00      1298
   macro avg       0.95      1.00      0.97      1298
weighted avg       1.00      1.00      1.00      1298

[[1279    2]
 [   0   17]]


KERNEL: sigmoid
              precision    recall  f1-score   support

         0.0       0.99      0.98      0.98      1281
         1.0       0.00      0.00      0.00        17

    accuracy                           0.97      1298
   macro avg       0.49      0.49      0.49      1298
weighted avg       0.97      0.97      0.97      1298

[[1254   27]
 [  17    0]]